/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponse } from './userResponse';

export interface AuthResponse {
  accessToken: string;
  expiresAt: string;
  user: UserResponse;
}
