/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ChatCitationResponse } from './chatCitationResponse';

export interface ChatAnswerResponse {
  question: string;
  answer: string;
  grounded: boolean;
  citations: ChatCitationResponse[];
  /** @nullable */
  model?: string | null;
  inputTokens: number;
  outputTokens: number;
}
