/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MessageSourceResponse } from './messageSourceResponse';

export interface ChatMessageResponse {
  id: string;
  role: string;
  content: string;
  /** @nullable */
  grounded?: boolean | null;
  /** @nullable */
  model?: string | null;
  inputTokens: number;
  outputTokens: number;
  createdAt: string;
  sources: MessageSourceResponse[];
}
