/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ConfirmUploadRequest {
  /**
     * @minLength 0
     * @maxLength 400
     */
  publicId: string;
  /**
     * @minLength 1
     * @maxLength 260
     */
  fileName: string;
}
