/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ChatMessageResponse } from './chatMessageResponse';

export interface ConversationResponse {
  id: string;
  documentId: string;
  /** @nullable */
  documentName?: string | null;
  title: string;
  createdAt: string;
  updatedAt: string;
  messages: ChatMessageResponse[];
}
