/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateDocumentRequest {
  fileName?: string;
  contentType?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  fileSize?: number | string;
}
