/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface DocumentPageResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageNumber: number | string;
  text: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  wordCount: number | string;
}
