/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentPageResponse } from './documentPageResponse';

export interface DocumentTextResponse {
  documentId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  wordCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  characterCount: number | string;
  extractedAt: string;
  pages: DocumentPageResponse[];
}
