/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface DocumentResponse {
  id: string;
  fileName: string;
  originalFileName: string;
  contentType: string;
  fileSize: number;
  status: string;
  /** @nullable */
  errorMessage?: string | null;
  createdAt: string;
  /** @nullable */
  processedAt?: string | null;
}
