/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentPageResponse } from './documentPageResponse';

export interface DocumentTextResponse {
  documentId: string;
  pageCount: number;
  wordCount: number;
  characterCount: number;
  extractedAt: string;
  pages: DocumentPageResponse[];
}
