/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentChunkResponse } from './documentChunkResponse';

export interface DocumentChunksResponse {
  documentId: string;
  totalCount: number;
  offset: number;
  limit: number;
  chunkSize: number;
  chunkOverlap: number;
  chunks: DocumentChunkResponse[];
}
