/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterRequest {
  /**
     * @minLength 2
     * @maxLength 120
     */
  name: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  email: string;
  /**
     * @minLength 8
     * @maxLength 128
     */
  password: string;
}
