/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SemanticSearchRequest {
  /**
     * @minLength 3
     * @maxLength 2000
     */
  query: string;
  /**
     * @minimum 1
     * @maximum 50
     * @nullable
     */
  topK?: number | null;
  /** @nullable */
  documentId?: string | null;
}
