/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SemanticMatchResponse } from './semanticMatchResponse';

export interface SemanticSearchResponse {
  query: string;
  similarityThreshold: number;
  matches: SemanticMatchResponse[];
}
