/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SemanticSearchRequest {
  query: string;
  /** @nullable */
  topK?: number | null;
  /** @nullable */
  documentId?: string | null;
}
