/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SemanticMatchResponse {
  documentId: string;
  fileName: string;
  chunkIndex: number;
  pageNumber: number;
  endPageNumber: number;
  similarity: number;
  text: string;
}
