/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface StartConversationRequest {
  documentId: string;
  /**
     * @minLength 3
     * @maxLength 2000
     * @nullable
     */
  question?: string | null;
}
