/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateProfileRequest {
  /**
     * @minLength 2
     * @maxLength 120
     */
  name: string;
}
