/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UploadTicketResponse {
  uploadUrl: string;
  apiKey: string;
  publicId: string;
  timestamp: number;
  signature: string;
  resourceType: string;
  maxFileSizeBytes: number;
}
