/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UploadTicketResponse {
  uploadUrl: string;
  apiKey: string;
  publicId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  timestamp: number | string;
  signature: string;
  resourceType: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  maxFileSizeBytes: number | string;
}
