/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UploadTicketRequest {
  /**
     * @minLength 1
     * @maxLength 260
     */
  fileName: string;
  /**
     * @minimum 1
     * @maximum 9223372036854776000
     */
  fileSize?: number;
}
