/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UsageResponse {
  since: string;
  embeddingCalls: number;
  embeddingInputTokens: number;
  chatCalls: number;
  chatInputTokens: number;
  chatOutputTokens: number;
}
