/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DocuMind.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UserResponse {
  id: string;
  name: string;
  email: string;
  createdAt: string;
}
