using DocuMind.Application.Interfaces;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace DocuMind.Infrastructure.Storage;

/// <summary>
/// Filesystem-backed storage for local development. Swapping in S3 or Azure Blob later means
/// replacing this class and nothing else — no caller interprets a storage key.
/// </summary>
public class LocalFileStorageService : IFileStorageService
{
    private const int CopyBufferBytes = 81_920;

    private readonly string _root;
    private readonly ILogger<LocalFileStorageService> _logger;

    public LocalFileStorageService(
        IOptions<StorageOptions> options,
        ILogger<LocalFileStorageService> logger)
    {
        _root = Path.GetFullPath(options.Value.Local.UploadDirectory);
        _logger = logger;

        Directory.CreateDirectory(_root);
    }

    public async Task<StoredFileResult> SaveAsync(
        Stream content,
        string originalFileName,
        CancellationToken cancellationToken = default)
    {
        // The name on disk is generated, never taken from the upload — that is what makes a
        // malicious filename harmless. Only the extension is carried over, and it has already
        // been checked against the allow-list.
        var extension = Path.GetExtension(Path.GetFileName(originalFileName)).ToLowerInvariant();
        var storedFileName = $"{Guid.NewGuid():N}{extension}";

        // Date shards keep a single directory from accumulating every upload ever made.
        var relativeKey = $"{DateTime.UtcNow:yyyy/MM/dd}/{storedFileName}";
        var absolutePath = ResolvePath(relativeKey);

        Directory.CreateDirectory(Path.GetDirectoryName(absolutePath)!);

        if (content.CanSeek)
        {
            content.Position = 0;
        }

        long written;

        // FileMode.CreateNew rather than Create: a GUID collision should fail loudly instead of
        // silently overwriting somebody else's document.
        await using (var file = new FileStream(
            absolutePath,
            FileMode.CreateNew,
            FileAccess.Write,
            FileShare.None,
            CopyBufferBytes,
            useAsync: true))
        {
            await content.CopyToAsync(file, CopyBufferBytes, cancellationToken);
            written = file.Length;
        }

        _logger.LogInformation("Stored upload at {StorageKey} ({Bytes} bytes)", relativeKey, written);

        return new StoredFileResult(storedFileName, relativeKey, written);
    }

    public Task<Stream> OpenAsync(string storageKey, CancellationToken cancellationToken = default)
    {
        var path = ResolvePath(storageKey);

        if (!File.Exists(path))
        {
            throw new FileNotFoundException($"No stored file for key '{storageKey}'.", path);
        }

        Stream stream = new FileStream(
            path,
            FileMode.Open,
            FileAccess.Read,
            FileShare.Read,
            CopyBufferBytes,
            useAsync: true);

        return Task.FromResult(stream);
    }

    public Task DeleteAsync(string storageKey, CancellationToken cancellationToken = default)
    {
        try
        {
            var path = ResolvePath(storageKey);

            if (File.Exists(path))
            {
                File.Delete(path);
                _logger.LogInformation("Deleted stored file {StorageKey}", storageKey);
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            // Best-effort: a leftover file is cheaper than failing the caller's delete.
            _logger.LogWarning(ex, "Could not delete stored file {StorageKey}", storageKey);
        }

        return Task.CompletedTask;
    }

    /// <summary>
    /// Resolves a key beneath the storage root, refusing anything that climbs out of it. Keys are
    /// generated by this class, but a corrupted or tampered database value must not be able to
    /// reach arbitrary paths on the host.
    /// </summary>
    private string ResolvePath(string storageKey)
    {
        var path = Path.GetFullPath(Path.Combine(_root, storageKey));

        // Comparing against the root plus a separator stops "/uploads-evil" passing a naive
        // StartsWith check against "/uploads".
        var rootWithSeparator = _root.EndsWith(Path.DirectorySeparatorChar)
            ? _root
            : _root + Path.DirectorySeparatorChar;

        if (!path.StartsWith(rootWithSeparator, StringComparison.OrdinalIgnoreCase))
        {
            throw new UnauthorizedAccessException(
                $"Storage key '{storageKey}' resolves outside the storage root.");
        }

        return path;
    }
}
